from __future__ import annotations

from .contracts import (
    CandidateNode,
    DemotedItem,
    EvidenceClass,
    EvidenceSpan,
    ExtractedClaim,
    ExtractedEdge,
    ExtractedMethodSettingLink,
    ExtractedNode,
    ExtractedOutcome,
    ExtractedSetting,
    ExtractedSettingEdge,
    ExtractionCaps,
    ExtractionValidationError,
    ExtractionValidationReport,
    LocalEntityResolutionTask,
    MechanismSignature,
    PaperGraph,
    PaperExtraction,
    ProblemStatement,
    ResolutionRelationKind,
    ValidationSeverity,
)
from .evidence import select_evidence_spans, select_model_draft_spans
from .resolution import build_local_entity_resolution_tasks
from .validators import validate_extraction

__all__ = [
    "CandidateNode",
    "DemotedItem",
    "EvidenceClass",
    "EvidenceSpan",
    "ExtractedClaim",
    "ExtractedEdge",
    "ExtractedMethodSettingLink",
    "ExtractedNode",
    "ExtractedOutcome",
    "ExtractedSetting",
    "ExtractedSettingEdge",
    "ExtractionCaps",
    "ExtractionValidationError",
    "ExtractionValidationReport",
    "LocalEntityResolutionTask",
    "MechanismSignature",
    "PaperGraph",
    "PaperExtraction",
    "ProblemStatement",
    "ResolutionRelationKind",
    "ValidationSeverity",
    "build_local_entity_resolution_tasks",
    "select_evidence_spans",
    "select_model_draft_spans",
    "validate_extraction",
]
